help_text = """
Playferrous terminal interface

While in a session, server commands may still be executed by prefixing them with a `/`
"""

[[group]]
help_text = "Games:"

[[group.command]]
name = "games"
args = "<filters>"

[[group.command]]
name = "game"
args = "<game-id>"

[[group.command]]
name = "retire"
args = "<game-id>"

[[group]]
help_text = "Proposals:"

[[group.command]]
name = "proposals"
args = "<filters>"

[[group.command]]
name = "propose"
args = "<game-type>"

[[group.command]]
name = "withdraw"
args = "<proposal-id>"

[[group.command]]
name = "invite"
args = "<user-or-group-id>"

[[group]]
help_text = "Sessions:"

[[group.command]]
name = "sessions"

[[group.command]]
name = "enter"
args = "<session-id>"

[[group.command]]
name = "exit"

[[group]]
help_text = "Friends:"

[[group.command]]
name = "friends"

[[group]]
help_text = "Groups:"

[[group.command]]
name = "groups"

[[group]]
help_text = "Messages:"

[[group.command]]
name = "messages"

[[group.command]]
name = "read"
args = "<message-id>"

[[group]]
help_text = "Requests:"

[[group.command]]
name = "accept"
args = "<request-id>"

[[group.command]]
name = "decline"
args = "<request-id>"

[[group.command]]
name = "cancel"
args = "<request-id>"

[[group]]
help_text = "Misc:"

[[group.command]]
name = "help"
args = "<command>"
